//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityWebModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Security
    {
        public int Id { get; set; }
        public int LocatesId { get; set; }
        public string SecurityCode { get; set; }
        public string ISIN { get; set; }
        public string Sedol { get; set; }
        public string Cusip { get; set; }
        public string RIC { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tbl_Locates tbl_Locates { get; set; }
    }
}
